#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v20
# autospec commit: f35655a
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : akonadi-mime
Version  : 24.08.2
Release  : 79
URL      : https://download.kde.org/stable/release-service/24.08.2/src/akonadi-mime-24.08.2.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.08.2/src/akonadi-mime-24.08.2.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.08.2/src/akonadi-mime-24.08.2.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : Libraries and daemons to implement basic email handling
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: akonadi-mime-bin = %{version}-%{release}
Requires: akonadi-mime-data = %{version}-%{release}
Requires: akonadi-mime-lib = %{version}-%{release}
Requires: akonadi-mime-license = %{version}-%{release}
Requires: akonadi-mime-locales = %{version}-%{release}
BuildRequires : akonadi-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules shared-mime-info
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kmime-dev
BuildRequires : libxslt-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Akonadi Mime #
Akonadi Mime is a library that effectively bridges the type-agnostic API of
the Akonadi client libraries and the domain-specific KMime library. It provides
jobs, models and other helpers to make working with emails through Akonadi easier.

%package bin
Summary: bin components for the akonadi-mime package.
Group: Binaries
Requires: akonadi-mime-data = %{version}-%{release}
Requires: akonadi-mime-license = %{version}-%{release}

%description bin
bin components for the akonadi-mime package.


%package data
Summary: data components for the akonadi-mime package.
Group: Data

%description data
data components for the akonadi-mime package.


%package dev
Summary: dev components for the akonadi-mime package.
Group: Development
Requires: akonadi-mime-lib = %{version}-%{release}
Requires: akonadi-mime-bin = %{version}-%{release}
Requires: akonadi-mime-data = %{version}-%{release}
Provides: akonadi-mime-devel = %{version}-%{release}
Requires: akonadi-mime = %{version}-%{release}

%description dev
dev components for the akonadi-mime package.


%package lib
Summary: lib components for the akonadi-mime package.
Group: Libraries
Requires: akonadi-mime-data = %{version}-%{release}
Requires: akonadi-mime-license = %{version}-%{release}

%description lib
lib components for the akonadi-mime package.


%package license
Summary: license components for the akonadi-mime package.
Group: Default

%description license
license components for the akonadi-mime package.


%package locales
Summary: locales components for the akonadi-mime package.
Group: Default

%description locales
locales components for the akonadi-mime package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n akonadi-mime-24.08.2
cd %{_builddir}/akonadi-mime-24.08.2
pushd ..
cp -a akonadi-mime-24.08.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728611234
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1728611234
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/akonadi-mime
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/akonadi-mime-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/akonadi-mime/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/akonadi-mime-%{version}/README.md.license %{buildroot}/usr/share/package-licenses/akonadi-mime/cadc9e08cb956c041f87922de84b9206d9bbffb2 || :
cp %{_builddir}/akonadi-mime-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/akonadi-mime/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/akonadi-mime-%{version}/serializers/akonadi_serializer_mail.desktop.license %{buildroot}/usr/share/package-licenses/akonadi-mime/864bc0eb28c73bd997ac19ff91935ab771846615 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libakonadi-kmime6
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/akonadi_benchmarker
/usr/bin/akonadi_benchmarker

%files data
%defattr(-,root,root,-)
/usr/share/akonadi/plugins/serializer/akonadi_serializer_mail.desktop
/usr/share/config.kcfg/specialmailcollections.kcfg
/usr/share/mime-packages/x-vnd.kde.contactgroup.xml
/usr/share/qlogging-categories6/akonadi-mime.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim6/AkonadiMime/Akonadi/AddressAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/CommandBase
/usr/include/KPim6/AkonadiMime/Akonadi/DispatchModeAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/DispatcherInterface
/usr/include/KPim6/AkonadiMime/Akonadi/ErrorAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/MDNStateAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/MarkAsCommand
/usr/include/KPim6/AkonadiMime/Akonadi/MessageFlags
/usr/include/KPim6/AkonadiMime/Akonadi/MessageFolderAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/MessageModel
/usr/include/KPim6/AkonadiMime/Akonadi/MessageParts
/usr/include/KPim6/AkonadiMime/Akonadi/MessageQueueJob
/usr/include/KPim6/AkonadiMime/Akonadi/MessageStatus
/usr/include/KPim6/AkonadiMime/Akonadi/MoveCommand
/usr/include/KPim6/AkonadiMime/Akonadi/NewMailNotifierAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/Pop3ResourceAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/RemoveDuplicatesJob
/usr/include/KPim6/AkonadiMime/Akonadi/SentActionAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/SentBehaviourAttribute
/usr/include/KPim6/AkonadiMime/Akonadi/SpecialMailCollections
/usr/include/KPim6/AkonadiMime/Akonadi/SpecialMailCollectionsDiscoveryJob
/usr/include/KPim6/AkonadiMime/Akonadi/SpecialMailCollectionsRequestJob
/usr/include/KPim6/AkonadiMime/Akonadi/StandardMailActionManager
/usr/include/KPim6/AkonadiMime/Akonadi/TransportAttribute
/usr/include/KPim6/AkonadiMime/akonadi-mime_version.h
/usr/include/KPim6/AkonadiMime/akonadi/addressattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/akonadi-mime_export.h
/usr/include/KPim6/AkonadiMime/akonadi/commandbase.h
/usr/include/KPim6/AkonadiMime/akonadi/dispatcherinterface.h
/usr/include/KPim6/AkonadiMime/akonadi/dispatchmodeattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/errorattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/markascommand.h
/usr/include/KPim6/AkonadiMime/akonadi/mdnstateattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/messageflags.h
/usr/include/KPim6/AkonadiMime/akonadi/messagefolderattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/messagemodel.h
/usr/include/KPim6/AkonadiMime/akonadi/messageparts.h
/usr/include/KPim6/AkonadiMime/akonadi/messagequeuejob.h
/usr/include/KPim6/AkonadiMime/akonadi/messagestatus.h
/usr/include/KPim6/AkonadiMime/akonadi/movecommand.h
/usr/include/KPim6/AkonadiMime/akonadi/newmailnotifierattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/pop3resourceattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/removeduplicatesjob.h
/usr/include/KPim6/AkonadiMime/akonadi/sentactionattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/sentbehaviourattribute.h
/usr/include/KPim6/AkonadiMime/akonadi/specialmailcollections.h
/usr/include/KPim6/AkonadiMime/akonadi/specialmailcollectionsdiscoveryjob.h
/usr/include/KPim6/AkonadiMime/akonadi/specialmailcollectionsrequestjob.h
/usr/include/KPim6/AkonadiMime/akonadi/standardmailactionmanager.h
/usr/include/KPim6/AkonadiMime/akonadi/transportattribute.h
/usr/lib64/cmake/KPim6AkonadiMime/KPim6AkonadiMimeConfig.cmake
/usr/lib64/cmake/KPim6AkonadiMime/KPim6AkonadiMimeConfigVersion.cmake
/usr/lib64/cmake/KPim6AkonadiMime/KPim6AkonadiMimeTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6AkonadiMime/KPim6AkonadiMimeTargets.cmake
/usr/lib64/libKPim6AkonadiMime.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKPim6AkonadiMime.so.6.2.2
/V3/usr/lib64/qt6/plugins/akonadi_serializer_mail.so
/usr/lib64/libKPim6AkonadiMime.so.6
/usr/lib64/libKPim6AkonadiMime.so.6.2.2
/usr/lib64/qt6/plugins/akonadi_serializer_mail.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/akonadi-mime/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/akonadi-mime/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/akonadi-mime/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/akonadi-mime/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/akonadi-mime/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/akonadi-mime/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/akonadi-mime/864bc0eb28c73bd997ac19ff91935ab771846615
/usr/share/package-licenses/akonadi-mime/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/akonadi-mime/cadc9e08cb956c041f87922de84b9206d9bbffb2
/usr/share/package-licenses/akonadi-mime/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f libakonadi-kmime6.lang
%defattr(-,root,root,-)

